AWSTemplateFormatVersion: '2010-09-09'
Description: 'ALB for Uploader application'

Parameters:
  EnvironmentName:
    Description: 'Application environment name'
    Type: String
  VPCId:
    Description: 'VPC ID'
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Description: 'Public Subnet 1 ID'
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2:
    Description: 'Public Subnet 2 ID'
    Type: AWS::EC2::Subnet::Id
  ALBSecurityGroup:
    Description: 'ALB Security Group ID'
    Type: AWS::EC2::SecurityGroup::Id
  ProjectTag:
    Description: 'Project tag to group related resources'
    Type: String
    Default: 'week_5_project'

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-uploader-alb
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-alb
        - Key: Project
          Value: !Ref ProjectTag 

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBDefaultTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-alb-listener
        - Key: Project
          Value: !Ref ProjectTag 

  ALBDefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Name: !Sub ${EnvironmentName}-uploader-tg
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-default-tg
        - Key: Project
          Value: !Ref ProjectTag 

Outputs:
  ALBArn:
    Description: 'ARN of the ALB'
    Value: !Ref ALB
    Export:
      Name: !Sub ${EnvironmentName}-Uploader-ALB-ARN
  ALBDNSName:
    Description: 'DNS name of the ALB'
    Value: !GetAtt ALB.DNSName
    Export:
      Name: !Sub ${EnvironmentName}-Uploader-ALB-DNS
  ALBListener:
    Description: 'ALB Listener ARN'
    Value: !Ref ALBListener
    Export:
      Name: !Sub ${EnvironmentName}-Uploader-ALB-Listener
  ALBDefaultTargetGroup:
    Description: 'Default Target Group ARN'
    Value: !Ref ALBDefaultTargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-Uploader-ALB-TG
