AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Cluster for Uploader application'

Parameters:
  EnvironmentName:
    Description: 'Application environment name'
    Type: String

  ProjectTag:
    Description: 'Project tag to group related resources'
    Type: String
    Default: 'week_5_project'

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvironmentName}-uploader-cluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
          Base: 1
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-ecs-cluster
        - Key: Project
          Value: !Ref ProjectTag 

  ECSAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [application-autoscaling.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: uploader-service-autoscaling
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'application-autoscaling:*'
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:PutMetricAlarm'
                  - 'ecs:DescribeServices'
                  - 'ecs:UpdateService'
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-ecs-autoscaling-role
        - Key: Project
          Value: !Ref ProjectTag

Outputs:
  ECSCluster:
    Description: 'ECS Cluster Name'
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${EnvironmentName}-Uploader-ECS-Cluster
  ECSAutoScalingRoleArn:
    Description: "Auto Scaling IAM Role ARN"
    Value: !GetAtt ECSAutoScalingRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-Uploader-ECSAutoScalingRoleArn
