AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Service for Uploader application'

Parameters:
  EnvironmentName:
    Description: 'Application environment name'
    Type: String
  ECSCluster:
    Description: 'ECS Cluster Name'
    Type: String
  ALBArn:
    Description: 'ARN of the ALB'
    Type: String
  ALBListener:
    Description: 'ALB Listener ARN'
    Type: String
  ECSSecurityGroup:
    Description: 'ECS Security Group ID'
    Type: AWS::EC2::SecurityGroup::Id
  PrivateSubnet1:
    Description: 'Private Subnet 1 ID'
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Description: 'Private Subnet 2 ID'
    Type: AWS::EC2::Subnet::Id
  S3BucketName:
    Description: 'Name of the S3 bucket for images'
    Type: String
  ECRRepoName:
    Description: 'Name of the ECR repository for the application'
    Type: String
  BlueTargetGroupArn:
    Type: String
    Description: "ARN of the Blue Target Group"
  GreenTargetGroupArn:
    Type: String
    Description: "ARN of the Green Target Group"
  AutoScalingRoleArn:
    Description: 'ARN of the IAM Role for ECS Auto Scaling'
    Type: String
  ProjectTag:
    Description: 'Project tag to group related resources'
    Type: String
    Default: 'week_5_project'


Resources:
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: uploader-ecs-execution-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:CreateLogGroup'  
                  - 'logs:DescribeLogStreams'
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-ecs-exec-role
        - Key: Project
          Value: !Ref ProjectTag 

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: uploader-s3-access-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - kms:Decrypt
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
                  - !Sub arn:aws:s3:::${S3BucketName}/*
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/scale-app/dev/aws/*

      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-ecs-task-role
        - Key: Project
          Value: !Ref ProjectTag

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-uploader-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: !Sub ${EnvironmentName}-uploader-container
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepoName}:latest
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          Environment:
            - Name: S3_BUCKET_NAME
              Value: !Ref S3BucketName
            - Name: ENVIRONMENT
              Value: !Ref EnvironmentName
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: AWS_S3_BUCKET
              Value: !Ref S3BucketName
          Secrets:
            - Name: AWS_ACCESS_KEY
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/scale-app/dev/aws/access_key
            - Name: AWS_SECRET_KEY
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/scale-app/dev/aws/secret_key
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-task-def
        - Key: Project
          Value: !Ref ProjectTag


  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${EnvironmentName}-uploader-service
      RetentionInDays: 7
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-ecs-logs
        - Key: Project
          Value: !Ref ProjectTag 

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${EnvironmentName}-uploader-service
      Cluster: !Ref ECSCluster
      DeploymentController:
        Type: CODE_DEPLOY
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      TaskDefinition: !Ref ECSTaskDefinition
      LoadBalancers:
        - ContainerName: !Sub ${EnvironmentName}-uploader-container
          ContainerPort: 80
          TargetGroupArn: !Ref BlueTargetGroupArn
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-uploader-ecs-service
        - Key: Project
          Value: !Ref ProjectTag 

  ECSServiceAutoScaling:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: ECSService
    Properties:
      MaxCapacity: 4
      MinCapacity: 2
      ResourceId: !Sub service/${ECSCluster}/${EnvironmentName}-uploader-service
      RoleARN: !Ref AutoScalingRoleArn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  CPUUtilizationScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${EnvironmentName}-uploader-cpu-scaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ECSServiceAutoScaling
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 50
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization

Outputs:
  ECSService:
    Description: 'ECS Service Name'
    Value: !Ref ECSService
    Export:
      Name: !Sub ${EnvironmentName}-Uploader-ECS-Service

  ECSTaskDefinitionArn:
    Description: 'ARN of the ECS Task Definition'
    Value: !Ref ECSTaskDefinition
    Export:
      Name: !Sub ${EnvironmentName}-Uploader-Task-Def
